version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: bronze_crime_raw
      - name: bronze_stopsearch_raw

models:
  - name: dim_date
    columns:
      - name: DateKey
        tests: [unique, not_null]
      - name: FullDate
      - name: Year
      - name: Month
      - name: Day 
      - name: MonthName 
      - name: Season 
      - name: Weekday 
      - name: WeekdayType 
      - name: Holiday 

  - name: dim_location
    columns:
      - name: LocationKey
        tests: [unique, not_null]
      - name: LSOACode
      - name: LSOAName
      - name: LocationDescription 
      - name: Latitude 
      - name: Longitude
  
  - name: dim_crime_outcome
    columns:
      - name: CrimeOutcomeKey
        tests: [unique, not_null]
      - name: OutcomeName
      - name: IsResolved
  
  - name: dim_demographics
    columns: 
      - name: DemographicsKey
        tests: [unique, not_null]
      - name: Gender
      - name: AgeRange
      - name: EthnicitySelf 
      - name: EthnicityOfficer

  - name: dim_search_outcome
    columns:
      - name: SearchOutcomeKey
        tests: [unique, not_null]
      - name: OutcomeName
      - name: IsSuccessful

  - name: dim_search_detail
    columns:
      - name: SearchDetailKey
        tests: [unique, not_null]
      - name: LegislationUsed
      - name: ObjectOfSearch

  - name: fact_crime
    columns:
      - name: CrimeFactID
        tests: [unique, not_null]
      - name: CrimeID
      - name: DateKey
      - name: LocationKey
      - name: PoliceForce
      - name: CrimeType
      - name: CrimeOutcomeKey 
      - name: IncidentCount

  - name: fact_stop_search
    columns:
      - name: StopFactID
        tests: [unique, not_null]
      - name: StopID
      - name: DateKey
      - name: DemographicsKey 
      - name: SearchOutcomeKey
      - name: SearchDetailKey 
      - name: IsLinkedToObject
      - name: StopCount
